import { BEHistoricalSummaryOverviewDTO } from 'BEModels/backend-models.interface';

export const HistoricalSummarySampleReturn: BEHistoricalSummaryOverviewDTO = {
  "GroupIdentifierWithInclusiveOptions":{
    "source":"Default",
    "date":"2020-03-03T00:00:00-05:00",
    "groupOptionValues":{
      "SecurityType":[
        "Bond"
      ],
      "Ccy":[
        "USD"
      ],
      "CouponType":[
        "Float"
      ],
      "BackendTenor":[
        "None"
      ],
      "BailInStatus":[
        "Not bail in"
      ],
      "Country":[
        "US"
      ],
      "Industry":[
        "Medical Equipment & Devices Manufacturing"
      ],
      "IsNewIssue":[
        "N"
      ],
      "IsOnTheRun":[
        "N"
      ],
      "MaturityType":[
        "Bullet"
      ],
      "ObligorId":[
        "1278"
      ],
      "QuotedToday":[
        "Y"
      ],
      "RatingNoNotch":[
        "BBB"
      ],
      "RatingBucket":[
        "Xover"
      ],
      "Sector":[
        "Health Care"
      ],
      "SecurityIdentifier":[
        "2508"
      ],
      "Seniority":[
        "SR"
      ],
      "SubIndustry":[
        "Drug Delivery Systems"
      ],
      "Tenor":[
        "2Y"
      ],
      "Ticker":[
        "BDX"
      ],
      "IsOwned":[
        "Y"
      ],
      "PrimaryPmName":[
        "DJ"
      ],
      "BackupPmName":[
        "PM"
      ],
      "ResearchName":[
        "AG"
      ],
      "PortfolioShortName":[
        "None"
      ],
      "StrategyName":[
        "None"
      ],
      "Owner":[
        "None"
      ]
    },
    "groupFilters":{

    }
  },
  "Mom":{
    "BaseSecurity":{
      "databaseSource":"Citi",
      "startDate":"2020-02-03T00:00:00-05:00",
      "endDate":"2020-03-03T00:00:00-05:00",
      "metricName":"Spread",
      "historicalLevel":{
        "targetSecurityIdentifier":null,
        "startMetric":75.0092,
        "endMetric":null,
        "maxMetric":null,
        "minMetric":null,
        "timeSeries":{

        },
        "isLevelRange":true,
        "isBasisRange":false,
        "isValid":false
      },
      "historicalBasis":null,
      "security":{
        "isSovereign":false,
        "isGovt":false,
        "isEm":false,
        "securityIdentifier":"2508",
        "ccy":"USD",
        "country":"US",
        "industry":"Medical Equipment & Devices Manufacturing",
        "name":"BDX FRN 06/06/2022 Bullet USD SENIOR_UNSECURED",
        "genericSeniority":"SR",
        "globalIdentifier":"US075887BU29",
        "obligorName":"BECTON DICKINSON AND CO",
        "obligorId":1278,
        "paymentRank":"SR UNSECURED",
        "sector":"Health Care",
        "securitySubType":"FRN",
        "subIndustry":"Drug Delivery Systems",
        "ticker":"BDX",
        "metrics":{
          "isFixedForLife":false,
          "isFixedToFloatInFixed":false,
          "isFloat":true,
          "isOnTheRun":false,
          "isNewIssue":false,
          "benchmarkSecurityIdentifier":null,
          "benchmarkName":null,
          "underlyingSecurityId":-1,
          "zSpread":0,
          "gSpread":0,
          "yieldWorst":0,
          "amtOutstanding":500000000,
          "marketValue":508136980,
          "workoutTerm":2.2603,
          "ratingDouble":14,
          "isRated":true,
          "rating":"BBB-",
          "ratingNoNotch":"BBB",
          "ratingBucket":"Xover",
          "price":0,
          "spread":0,
          "isIndex":false
        },
        "deltaMetrics":{
          "Dod":{
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "ratingDouble":-1,
            "price":0,
            "spread":0
          },
          "Wow":{
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "ratingDouble":-1,
            "price":0,
            "spread":0
          },
          "Mtd":{
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "ratingDouble":-1,
            "price":0,
            "spread":0
          },
          "Mom":{
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "ratingDouble":-1,
            "price":0,
            "spread":0
          },
          "Ytd":{
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "ratingDouble":-1,
            "price":0,
            "spread":0
          },
          "Yoy":{
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "ratingDouble":0,
            "price":0,
            "spread":0
          }
        },
        "firmPosition":{
          "partitionOptionValues":{
            "PortfolioShortName":[
              "AGB",
              "DOF"
            ],
            "StrategyName":[
              "Short Carry"
            ]
          },
          "mark":{
            "driver":"Spread",
            "enteredTime":null,
            "user":null,
            "value":62,
            "price": 72,
            "spread": 73

          },
          "primaryPmName":"DJ",
          "backupPmName":"PM",
          "researchName":"AG",
          "owners":[
            "DJ",
            "PM",
            "AG"
          ],
          "date":"2020-03-04T00:00:00-05:00",
          "securityIdentifier":"2508",
          "quantity":3354000,
          "hedgeFactor":1,
          "cs01Cad":1001.3637936120001,
          "cs01Local":1001.3637936120001
        },
        "securityType":"Bond",
        "maturityType":"Bullet"
      },
      "rank":0,
      "name":"BDX FRN 06/06/2022 Bullet USD SENIOR_UNSECURED",
      "isSecurityHistoricalSummary":true,
      "isGroupHistoricalSummary":false
    },
    "Group":{
      "databaseSource":"Citi",
      "startDate":"2020-02-03T00:00:00-05:00",
      "endDate":"2020-03-03T00:00:00-05:00",
      "metricName":"Spread",
      "historicalLevel":{
        "targetSecurityIdentifier":null,
        "startMetric":null,
        "endMetric":null,
        "maxMetric":null,
        "minMetric":null,
        "timeSeries":{

        },
        "isLevelRange":true,
        "isBasisRange":false,
        "isValid":false
      },
      "historicalBasis":{
        "targetSecurityIdentifier":"2508",
        "startMetric":null,
        "endMetric":null,
        "maxMetric":null,
        "minMetric":null,
        "timeSeries":{

        },
        "isLevelRange":false,
        "isBasisRange":true,
        "isValid":false
      },
      "group":{
        "ccy":"USD",
        "securityType":"Bond",
        "couponType":"Float",
        "metrics":{
          "workoutTerm":2.2603,
          "ratingDouble":14,
          "price":0,
          "zSpread":0,
          "gSpread":0,
          "yieldWorst":0,
          "amtOutstanding":500000000,
          "marketValue":508136980,
          "spread":0,
          "tenor":"2Y",
          "backendTenor":"2Y",
          "propertyToNumSecurities":{
            "WorkoutTerm":1,
            "RatingDouble":1,
            "AmtOutstanding":1,
            "MarketValue":1
          },
          "isRated":true,
          "rating":"BBB-",
          "ratingNoNotch":"BBB",
          "ratingBucket":"NR",
          "isIndex":false
        },
        "deltaMetrics":{
          "Dod":{
            "ratingDouble":-1,
            "price":0,
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "spread":0,
            "tenor":null,
            "backendTenor":null,
            "propertyToNumSecurities":{
              "WorkoutTerm":1,
              "RatingDouble":1,
              "AmtOutstanding":1,
              "MarketValue":1
            }
          },
          "Wow":{
            "ratingDouble":-1,
            "price":0,
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "spread":0,
            "tenor":null,
            "backendTenor":null,
            "propertyToNumSecurities":{
              "WorkoutTerm":1,
              "RatingDouble":1,
              "AmtOutstanding":1,
              "MarketValue":1
            }
          },
          "Mtd":{
            "ratingDouble":-1,
            "price":0,
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "spread":0,
            "tenor":null,
            "backendTenor":null,
            "propertyToNumSecurities":{
              "WorkoutTerm":1,
              "RatingDouble":1,
              "AmtOutstanding":1,
              "MarketValue":1
            }
          },
          "Mom":{
            "ratingDouble":-1,
            "price":0,
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "spread":0,
            "tenor":null,
            "backendTenor":null,
            "propertyToNumSecurities":{
              "WorkoutTerm":1,
              "RatingDouble":1,
              "AmtOutstanding":1,
              "MarketValue":1
            }
          },
          "Ytd":{
            "ratingDouble":-1,
            "price":0,
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "spread":0,
            "tenor":null,
            "backendTenor":null,
            "propertyToNumSecurities":{
              "WorkoutTerm":1,
              "RatingDouble":1,
              "AmtOutstanding":1,
              "MarketValue":1
            }
          },
          "Yoy":{
            "ratingDouble":0,
            "price":0,
            "zSpread":0,
            "gSpread":0,
            "yieldWorst":0,
            "spread":0,
            "tenor":null,
            "backendTenor":null,
            "propertyToNumSecurities":{
              "WorkoutTerm":1,
              "RatingDouble":1,
              "AmtOutstanding":1,
              "MarketValue":1
            }
          }
        },
        "isValid":true,
        "groupIdentifier":{
          "source":"Default",
          "date":"2020-03-03T00:00:00-05:00",
          "groupOptionValues":{
            "Seniority":[
              "SR"
            ],
            "RatingNoNotch":[
              "BBB"
            ],
            "Sector":[
              "Health Care"
            ],
            "Industry":[
              "Medical Equipment & Devices Manufacturing"
            ],
            "Tenor":[
              "2Y"
            ],
            "Country":[
              "US"
            ],
            "Ccy":[
              "USD"
            ],
            "SecurityType":[
              "Bond"
            ],
            "CouponType":[
              "Float"
            ]
          },
          "groupFilters":{

          }
        },
        "source":"Default",
        "date":"2020-03-03T00:00:00-05:00",
        "numSecurities":1,
        "name":"Bond|USD|Float|SR|2Y|BBB|Health Car|Medical Eq|US",
        "type":"SingleSecurityGroup"
      },
      "rank":0,
      "name":"Bond|USD|Float|SR|2Y|BBB|Health Car|Medical Eq|US",
      "isSecurityHistoricalSummary":false,
      "isGroupHistoricalSummary":true
    },
    "Top":[

    ],
    "Bottom":[

    ]
  }
}
