import { BEFetchAllTradeDataReturn } from 'BEModels/backend-models.interface';

export const PortfolioList: BEFetchAllTradeDataReturn = {
  "numberOfSecurities":584,
  "securityDtos":{
    "groupIdentifier":{
      "source":"Default",
      "date":"2020-03-03T00:00:00-05:00",
      "groupOptionValues":{

      },
      "groupFilters":{
        "PortfolioShortName":[
          "AGB"
        ]
      }
    },
    "securityDtos":{
      "146":{
        "securityIdentifier":"146",
        "security":{
          "isSovereign":false,
          "isGovt":false,
          "isEm":false,
          "securityIdentifier":"146",
          "ccy":"USD",
          "country":"US",
          "industry":"Pipeline",
          "name":"NGPLCO 7.768 12/15/2037 Bullet USD 144A SENIOR_SECURED",
          "genericSeniority":"SR",
          "globalIdentifier":"US62912XAC83",
          "obligorName":"NGPL PIPECO LLC",
          "obligorId":949,
          "paymentRank":"SR UNSECURED",
          "sector":"Energy",
          "securitySubType":"Bond",
          "subIndustry":"Pipelines",
          "ticker":"NGPLCO",
          "metrics":{
            "isFixedForLife":true,
            "isFixedToFloatInFixed":false,
            "isFloat":false,
            "isOnTheRun":false,
            "isNewIssue":false,
            "benchmarkSecurityIdentifier":"63089",
            "benchmarkName":"T 2.375 11/15/2049 USD",
            "underlyingSecurityId":-1,
            "zSpread":0.0,
            "gSpread":0.0,
            "yieldWorst":0.0,
            "amtOutstanding":500000000.0,
            "marketValue":662250065.0,
            "workoutTerm":17.7973,
            "ratingDouble":14.0,
            "isRated":true,
            "rating":"BBB-",
            "ratingNoNotch":"BBB",
            "ratingBucket":"IG",
            "price":0.0,
            "spread":0.0,
            "isIndex":false
          },
          "deltaMetrics":{
            "Dod":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            },
            "Wow":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            },
            "Mtd":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            },
            "Mom":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            },
            "Ytd":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            },
            "Yoy":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            }
          },
          "firmPosition":{
            "partitionOptionValues":{
              "PortfolioShortName":[
                "AGB",
                "CIP",
                "DOF",
                "SOF",
                "STIP"
              ],
              "StrategyName":[
                "LTOV - Spread"
              ]
            },
            "mark":{
              "driver":"Spread",
              "enteredTime":"2020-03-04T15:47:16.329",
              "user":"IL",
              "value":345.0
            },
            "primaryPmName":"IL",
            "backupPmName":"DM",
            "researchName":"AG",
            "owners":[
              "IL",
              "DM",
              "AG"
            ],
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"146",
            "quantity":24391000.0,
            "hedgeFactor":1.0,
            "cs01Cad":46382.86001921,
            "cs01Local":46382.86001921
          },
          "securityType":"Bond",
          "maturityType":"Bullet"
        },
        "bestQuotes":{
          "bestPriceQuote":{
            "isValid":true,
            "quoteMetric":"Price",
            "bidQuoteType":"Run",
            "bidDealer":"BARC",
            "bidTime":"2020-03-04T07:31:31",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Run",
            "askDealer":"BARC",
            "askTime":"2020-03-04T07:31:31",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":130.56700134277344,
            "askQuantity":0,
            "askQuoteValue":131.96800231933594,
            "globalIdentifier":"US62912XAC83"
          },
          "bestSpreadQuote":{
            "isValid":true,
            "quoteMetric":"Spread",
            "bidQuoteType":"Run",
            "bidDealer":"BARC",
            "bidTime":"2020-03-04T07:31:31",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Run",
            "askDealer":"BARC",
            "askTime":"2020-03-04T07:31:31",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":350.0,
            "askQuantity":0,
            "askQuoteValue":340.0,
            "globalIdentifier":"US62912XAC83"
          },
          "bestYieldQuote":{
            "isValid":true,
            "quoteMetric":"Yield",
            "bidQuoteType":"Run",
            "bidDealer":"BARC",
            "bidTime":"2020-03-04T07:31:31",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Run",
            "askDealer":"BARC",
            "askTime":"2020-03-04T07:31:31",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":5.125999927520752,
            "askQuantity":0,
            "askQuoteValue":5.026000022888184,
            "globalIdentifier":"US62912XAC83"
          }
        },
        "positions":[
          {
            "partitionOptionValue":{
              "PortfolioShortName":"AGB",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"146",
            "quantity":256000.0,
            "cs01Cad":486.81940736,
            "cs01Local":486.81940736
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"CIP",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"146",
            "quantity":1458000.0,
            "cs01Cad":2772.58865598,
            "cs01Local":2772.58865598
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"DOF",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"146",
            "quantity":9157000.0,
            "cs01Cad":17413.30200467,
            "cs01Local":17413.30200467
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"SOF",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"146",
            "quantity":8635000.0,
            "cs01Cad":16420.64680685,
            "cs01Local":16420.64680685
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"STIP",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"146",
            "quantity":4885000.0,
            "cs01Cad":9289.50314435,
            "cs01Local":9289.50314435
          }
        ]
      },
      "21282":{
        "securityIdentifier":"21282",
        "security":{
          "isSovereign":false,
          "isGovt":false,
          "isEm":false,
          "securityIdentifier":"21282",
          "ccy":"USD",
          "country":"US",
          "industry":"Transportation & Logistics",
          "name":"NAV 6.625 11/01/2025 Callable USD 144A SENIOR_UNSECURED",
          "genericSeniority":"SR",
          "globalIdentifier":"US63934EAT55",
          "obligorName":"NAVISTAR INTERNATIONAL CORP",
          "obligorId":550,
          "paymentRank":"SR UNSECURED",
          "sector":"Industrials",
          "securitySubType":"Bond",
          "subIndustry":"Auto-Med&Heavy Duty Trks",
          "ticker":"NAV",
          "metrics":{
            "isFixedForLife":true,
            "isFixedToFloatInFixed":false,
            "isFloat":false,
            "isOnTheRun":true,
            "isNewIssue":false,
            "benchmarkSecurityIdentifier":"67120",
            "benchmarkName":"T 1.125 02/28/2022 USD",
            "underlyingSecurityId":-1,
            "zSpread":0.0,
            "gSpread":0.0,
            "yieldWorst":0.0,
            "amtOutstanding":1100000000.0,
            "marketValue":1171643264.0,
            "workoutTerm":1.6658,
            "ratingDouble":8.67,
            "isRated":true,
            "rating":"B",
            "ratingNoNotch":"B",
            "ratingBucket":"HY",
            "price":0.0,
            "spread":0.0,
            "isIndex":false
          },
          "deltaMetrics":{
            "Dod":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.67,
              "price":0.0,
              "spread":0.0
            },
            "Wow":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.67,
              "price":0.0,
              "spread":0.0
            },
            "Mtd":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.67,
              "price":0.0,
              "spread":0.0
            },
            "Mom":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.67,
              "price":0.0,
              "spread":0.0
            },
            "Ytd":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.67,
              "price":0.0,
              "spread":0.0
            },
            "Yoy":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.0,
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            }
          },
          "firmPosition":{
            "partitionOptionValues":{
              "PortfolioShortName":[
                "AGB",
                "DOF",
                "SOF"
              ],
              "StrategyName":[
                "LTOV - Special Situations"
              ]
            },
            "mark":{
              "driver":"Spread",
              "enteredTime":null,
              "user":null,
              "value":425.0
            },
            "primaryPmName":"DJ",
            "backupPmName":"PM",
            "researchName":"TW",
            "owners":[
              "DJ",
              "PM",
              "TW"
            ],
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"21282",
            "quantity":46554000.0,
            "hedgeFactor":1.0,
            "cs01Cad":9381.283174986,
            "cs01Local":9381.283174986
          },
          "securityType":"Bond",
          "maturityType":"Callable"
        },
        "bestQuotes":{
          "bestPriceQuote":{
            "isValid":true,
            "quoteMetric":"Price",
            "bidQuoteType":"Run",
            "bidDealer":"BAML",
            "bidTime":"2020-03-04T06:42:50",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Axe",
            "askDealer":"BAML",
            "askTime":"2020-03-04T06:42:50",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":103.5,
            "askQuantity":0,
            "askQuoteValue":104.5,
            "globalIdentifier":"US63934EAT55"
          },
          "bestSpreadQuote":{
            "isValid":true,
            "quoteMetric":"Spread",
            "bidQuoteType":"Run",
            "bidDealer":"BAML",
            "bidTime":"2020-03-04T06:42:50",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Axe",
            "askDealer":"BAML",
            "askTime":"2020-03-04T06:42:50",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":449.5429992675781,
            "askQuantity":0,
            "askQuoteValue":390.5010070800781,
            "globalIdentifier":"US63934EAT55"
          },
          "bestYieldQuote":{
            "isValid":true,
            "quoteMetric":"Yield",
            "bidQuoteType":"Run",
            "bidDealer":"BAML",
            "bidTime":"2020-03-04T06:42:50",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Axe",
            "askDealer":"BAML",
            "askTime":"2020-03-04T06:42:50",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":5.191999912261963,
            "askQuantity":0,
            "askQuoteValue":4.593999862670898,
            "globalIdentifier":"US63934EAT55"
          }
        },
        "positions":[
          {
            "partitionOptionValue":{
              "PortfolioShortName":"AGB",
              "StrategyName":"LTOV - Special Situations"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"21282",
            "quantity":1149000.0,
            "cs01Cad":231.539596341,
            "cs01Local":231.539596341
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"DOF",
              "StrategyName":"LTOV - Special Situations"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"21282",
            "quantity":19195000.0,
            "cs01Cad":3868.061402755,
            "cs01Local":3868.061402755
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"SOF",
              "StrategyName":"LTOV - Special Situations"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"21282",
            "quantity":26210000.0,
            "cs01Cad":5281.68217589,
            "cs01Local":5281.68217589
          }
        ]
      },
      "65979":{
        "securityIdentifier":"65979",
        "security":{
          "securityIdentifier":"65979",
          "ccy":"USD",
          "country":"US",
          "industry":"Entertainment Content",
          "name":"ALNMED FRN 02/05/2025 Bullet USD Loan",
          "genericSeniority":"SECURED",
          "globalIdentifier":"BL3287994",
          "obligorName":"ALLEN MEDIA LLC",
          "obligorId":7106,
          "paymentRank":"1L SR. SECD",
          "sector":"Communications",
          "securitySubType":"Loan",
          "subIndustry":"Motion Pictures&Services",
          "ticker":"ALNMED",
          "metrics":{
            "isFixedForLife":false,
            "isFixedToFloatInFixed":false,
            "isFloat":true,
            "isOnTheRun":false,
            "isNewIssue":false,
            "benchmarkSecurityIdentifier":null,
            "benchmarkName":null,
            "underlyingSecurityId":-1,
            "zSpread":0.0,
            "gSpread":0.0,
            "yieldWorst":7.354309,
            "amtOutstanding":530000000.0,
            "marketValue":525586393.0,
            "workoutTerm":6.9315,
            "ratingDouble":11.0,
            "isRated":true,
            "rating":"BB-",
            "ratingNoNotch":"BB",
            "ratingBucket":"HY",
            "price":98.75,
            "spread":-51.6,
            "isIndex":false
          },
          "deltaMetrics":{
            "Dod":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.043759,
              "ratingDouble":0.0,
              "price":-0.249995,
              "spread":26.41
            },
            "Wow":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.630743,
              "ratingDouble":0.0,
              "price":-1.448487,
              "spread":66.86
            },
            "Mtd":{
              "zSpread":0.0,
              "gSpread":0.0,
              "yieldWorst":0.033399,
              "ratingDouble":0.0,
              "price":-0.25,
              "spread":32.56
            },
            "Mom":null,
            "Ytd":null,
            "Yoy":null
          },
          "firmPosition":{
            "partitionOptionValues":{
              "PortfolioShortName":[
                "AGB",
                "SOF"
              ],
              "StrategyName":[
                "LTOV - Yield"
              ]
            },
            "mark":{
              "driver":"Price",
              "enteredTime":null,
              "user":null,
              "value":98.75
            },
            "primaryPmName":"PM",
            "backupPmName":"DJ",
            "researchName":"LC",
            "owners":[
              "PM",
              "DJ",
              "LC"
            ],
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"65979",
            "quantity":2000000.0,
            "hedgeFactor":1.0,
            "cs01Cad":1486.5836160000001,
            "cs01Local":1486.5836160000001
          },
          "securityType":"Loan",
          "maturityType":"Bullet"
        },
        "bestQuotes":null,
        "positions":[
          {
            "partitionOptionValue":{
              "PortfolioShortName":"AGB",
              "StrategyName":"LTOV - Yield"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"65979",
            "quantity":60000.0,
            "cs01Cad":44.59750848,
            "cs01Local":44.59750848
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"SOF",
              "StrategyName":"LTOV - Yield"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"65979",
            "quantity":1940000.0,
            "cs01Cad":1441.9861075200001,
            "cs01Local":1441.9861075200001
          }
        ]
      },
      "471|5Y":{
        "securityIdentifier":"471|5Y",
        "security":{
          "curveSubType":"MM14",
          "securityIdentifier":"471|5Y",
          "ccy":"EUR",
          "country":"DE",
          "industry":"Diversified Banks",
          "name":"DB CDS EUR SUB 5Y",
          "genericSeniority":"SUB",
          "globalIdentifier":"DB CDS EUR SUB 5Y",
          "obligorName":"DEUTSCHE BANK AG",
          "obligorId":237,
          "paymentRank":"SUBORDINATED",
          "sector":"Financials",
          "securitySubType":null,
          "subIndustry":"Diversified Banking Inst",
          "ticker":"DB",
          "metrics":{
            "isOnTheRun":true,
            "workoutTerm":4.8027,
            "ratingDouble":13.5,
            "isRated":true,
            "rating":"BBB-",
            "ratingNoNotch":"BBB",
            "ratingBucket":"Xover",
            "price":0.0,
            "spread":0.0,
            "isIndex":false
          },
          "deltaMetrics":{
            "Dod":{
              "ratingDouble":1.5,
              "price":0.0,
              "spread":0.0
            },
            "Wow":{
              "ratingDouble":1.5,
              "price":0.0,
              "spread":0.0
            },
            "Mtd":{
              "ratingDouble":1.5,
              "price":0.0,
              "spread":0.0
            },
            "Mom":{
              "ratingDouble":1.5,
              "price":0.0,
              "spread":0.0
            },
            "Ytd":{
              "ratingDouble":1.5,
              "price":0.0,
              "spread":0.0
            },
            "Yoy":{
              "ratingDouble":0.0,
              "price":0.0,
              "spread":0.0
            }
          },
          "firmPosition":{
            "partitionOptionValues":{
              "PortfolioShortName":[
                "AGB",
                "DOF",
                "SOF",
                "STIP"
              ],
              "StrategyName":[
                "LTOV - Spread",
                "HEDGE"
              ]
            },
            "mark":{
              "driver":"Spread",
              "enteredTime":"2020-03-04T14:06:46",
              "user":"RS",
              "value":269.0
            },
            "primaryPmName":"RS",
            "backupPmName":"DJ",
            "researchName":"LP",
            "owners":[
              "RS",
              "DJ",
              "LP"
            ],
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"471|5Y",
            "quantity":-25813000.0,
            "hedgeFactor":1.0,
            "cs01Cad":-15900.706719054,
            "cs01Local":-15900.706719054
          },
          "securityType":"Cds",
          "maturityType":"Bullet"
        },
        "bestQuotes":{
          "bestPriceQuote":null,
          "bestSpreadQuote":{
            "isValid":true,
            "quoteMetric":"Spread",
            "bidQuoteType":"Run",
            "bidDealer":"JPM",
            "bidTime":"2020-03-04T07:36:25",
            "bidVenue":"MSG1",
            "bidIsOld":true,
            "askQuoteType":"Run",
            "askDealer":"JPM",
            "askTime":"2020-03-04T07:36:25",
            "askVenue":"MSG1",
            "askIsOld":true,
            "isOffTheRunCds":false,
            "totalAxeBidQuantity":0,
            "totalAxeAskQuantity":0,
            "totalRunBidQuantity":0,
            "totalRunAskQuantity":0,
            "axeSkew":null,
            "totalSkew":null,
            "bidQuantity":0,
            "bidQuoteValue":255.0,
            "askQuantity":0,
            "askQuoteValue":270.0,
            "globalIdentifier":"DB CDS EUR SUB 5Y D14"
          },
          "bestYieldQuote":null
        },
        "positions":[
          {
            "partitionOptionValue":{
              "PortfolioShortName":"AGB",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"471|5Y",
            "quantity":-480000.0,
            "cs01Cad":-295.66752,
            "cs01Local":-295.66752
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"DOF",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"471|5Y",
            "quantity":-14233000.0,
            "cs01Cad":-8767.632989474,
            "cs01Local":-8767.632989474
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"SOF",
              "StrategyName":"LTOV - Spread"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"471|5Y",
            "quantity":-3620000.0,
            "cs01Cad":-2229.9206895800003,
            "cs01Local":-2229.9206895800003
          },
          {
            "partitionOptionValue":{
              "PortfolioShortName":"STIP",
              "StrategyName":"HEDGE"
            },
            "date":"2020-03-04T00:00:00-05:00",
            "securityIdentifier":"471|5Y",
            "quantity":-7480000.0,
            "cs01Cad":-4607.48552,
            "cs01Local":-4607.48552
          }
        ]
      }
    }
  }
}